name: Deploy infra to Dev

on:
  push:
    branches:
      - dev

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Initialize Terraform
        working-directory: ./envs/dev
        run: terraform init

      - name: Validate Terraform
        working-directory: ./envs/dev
        run: terraform validate

      - name: Get AKS service principal Credentials
        working-directory: ./envs/dev
        run: |
          export TF_VAR_appid=$(az keyvault secret show --name sp-neu-dev-aks-appid --vault-name "kv-neu-dev-all" --query value -o tsv)
          export TF_VAR_secret=$(az keyvault secret show --name sp-neu-dev-aks-secret --vault-name "kv-neu-dev-all" --query value -o tsv)

      - name: Plan Terraform
        working-directory: ./envs/dev
        run: terraform plan -out=tfplan
        env:
          TF_VAR_appid: ${{ secrets.TF_VAR_appid }}
          TF_VAR_secret: ${{ secrets.TF_VAR_secret }}

      - name: Apply Terraform
        working-directory: ./envs/dev
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_appid: ${{ secrets.TF_VAR_appid }}
          TF_VAR_secret: ${{ secrets.TF_VAR_secret }}
