name: Deploy infra to prd

on:
    push:
        branches:
            - prd

env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
    terraform-plan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Initialize Terraform
              working-directory: ./envs/prd
              run: terraform init

            - name: Validate Terraform
              working-directory: ./envs/prd
              run: terraform validate

            - name: Plan Terraform
              working-directory: ./envs/prd
              run: terraform plan -out=tfplan

    terraform-apply:
        runs-on: ubuntu-latest
        environment: prd

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Initialize Terraform
              working-directory: ./envs/prd
              run: terraform init

            - name: Validate Terraform
              working-directory: ./envs/prd
              run: terraform validate

            - name: Plan Terraform
              working-directory: ./envs/prd
              run: terraform plan -out=tfplan

            - name: Apply Terraform
              working-directory: ./envs/prd
              run: terraform apply -auto-approve tfplan
