name: Deploy infra to Dev

on:
  push:
    branches:
      - dev

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: ./envs/dev
        run: terraform init

      - name: Validate Terraform
        working-directory: ./envs/dev
        run: terraform validate

      - name: Plan Terraform
        working-directory: ./envs/dev
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        working-directory: ./envs/dev
        run: terraform apply -auto-approve tfplan

    apply-deployment:
        needs: terraform
        name: Apply external-dns deployment
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

          
            - name: Login to Azure
              uses: azure/login@v2
              with:
                  creds: |
                    {
                      "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
                      "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
                      "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                      "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
                    }
          
            - name: Apply deployment
              run: |
                  CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}
                  CLOUDFLARE_API_TOKEN_ENCODED=$(echo -n "${CLOUDFLARE_API_TOKEN}" | base64 -w 0)
                  sed -i "s#CLOUDFLARE_API_TOKEN_SECRET_VALUE#${CLOUDFLARE_API_TOKEN_ENCODED}#g" external-dns-deployment.yaml

                  az aks get-credentials --resource-group infra-rg-neu --name pecarmoaks

                  kubectl apply -f external-dns-deployment.yaml
                  kubectl rollout restart deployment/external-dns
