name: Deploy infra to uat

on:
    push:
        branches:
            - uat

env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
    terraform-plan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Initialize Terraform
              working-directory: ./envs/uat
              run: terraform init

            - name: Validate Terraform
              working-directory: ./envs/uat
              run: terraform validate

            - name: Plan Terraform
              working-directory: ./envs/uat
              run: terraform plan -out=tfplan

    approval-gate-application:
      name: "Approval Gate App"
      runs-on: ubuntu-20.04
      environment: uat
      needs: [terraform-plan]
      if: ${{ always() && (needs.terraform-plan.outputs.planExitcode == 2) }}
      steps:
        - run: echo "Approval required to proceed with the deployment."

    terraform-apply:
        runs-on: ubuntu-latest
        environment: uat

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Initialize Terraform
              working-directory: ./envs/uat
              run: terraform init

            - name: Validate Terraform
              working-directory: ./envs/uat
              run: terraform validate

            - name: Apply Terraform
              working-directory: ./envs/uat
              run: terraform apply -auto-approve
