name: Deploy infra to uat

on:
    push:
        branches:
            - uat

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
    terraform-plan:
        runs-on: ubuntu-latest
        environment: uat
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Initialize Terraform
              working-directory: ./envs/uat
              run: terraform init

            - name: Validate Terraform
              working-directory: ./envs/uat
              run: terraform validate

            - name: Plan Terraform
              working-directory: ./envs/uat
              run: terraform plan -out=tfplan

    approval-gate:
      name: "Approval Gate App"
      runs-on: ubuntu-20.04
      environment: uat-approvers
      needs: [terraform-plan]
      if: ${{ always() && (needs.terraform-plan.outputs.planExitcode == 2) }}
      steps:
        - run: echo "Approval required to proceed with the deployment."

    terraform-apply:
        runs-on: ubuntu-latest
        environment: uat
        needs: [terraform-plan, approval-gate]
        if: ${{ always() && (needs.approval-gate.result == 'Success') }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Initialize Terraform
              working-directory: ./envs/uat
              run: terraform init

            - name: Validate Terraform
              working-directory: ./envs/uat
              run: terraform validate

            - name: Apply Terraform
              working-directory: ./envs/uat
              run: terraform apply -auto-approve
