name: Deploy infra to Dev

on:
  push:
    branches:
      - dev

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: ./envs/dev
        run: terraform init

      - name: Validate Terraform
        working-directory: ./envs/dev
        run: terraform validate

      - name: Plan Terraform
        working-directory: ./envs/dev
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        working-directory: ./envs/dev
        run: terraform apply -auto-approve tfplan
